// Code generated by goctl. DO NOT EDIT.
package types

type MessageProperties struct {
	Url     string   `json:"url"`
	Name    string   `json:"name"`
	Message string   `json:"message"`
	Phones  []string `json:"phones"`
	Method  string   `json:"method,default=GET"`
	Timeout int   `json:"timeout,default=2000"`
}
